// Automatically generated by astro-icon
// d86d17b545d5033db70258f261b20de9f5c40743c113374aaf45c139ffe297a2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "heart-empty"
		| "heart-full";
}